# Generated by Django 3.2.5 on 2021-07-21 02:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'meal')},
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together={('user', 'meal')},
        ),
    ]
